DevTools: Add build target
facebook/react pull request #18994
Opened 2020-05-25 08:19 UTC by bl00mber

resolve #18843
another option is just use process.env.TARGET

2020-10-09 11:54 UTC, bl00mber commented
@bvaughn

2020-10-09 13:44 UTC, bvaughn requested changes
IMO this feels a little over-architected for what it is. If you renamed "target flags" to be "feature flags" (a parallel to `shared/ReactFeatureFlags`) then maybe it would be okay. I have had thoughts about adding a feature flag system for a while so that I could try new things out in the internal Facebook build without committing to releasing them to open source until it's stable.

2020-10-09 13:44 UTC, bvaughn commented on packages/react-devtools-shared/config/resolveTarget.js
> +  }
```suggestion
  switch (target) {
    case 'local':
    case 'remote':
    case 'inline':
    case 'standalone':
    case 'backend':
      flagsPath = 'TargetFlags.default';
      break;
    case 'extension':
      flagsPath = 'TargetFlags.extension';
      break;
    default:
      console.error('invalid TARGET:', target);
      process.exit(1);
  }
```

2020-10-09 13:44 UTC, bvaughn commented on packages/react-devtools-shared/config/resolveTarget.js
> +function validateWebpackTarget(target) {
This method seems unnecessary since `resolveTargetFlags` also errors and exits.

2020-10-12 14:29 UTC, bvaughn reviewed
This PR does not resolve #18843 for reasons I mentioned in my comment on `src/hooks`. (Now we just get an error from a different import.)

We *could* solve this problem by adding an inline `process.env.NODE_ENV` type check which is what I think I'll do.

I think there's still some value for continuing the momentum of this PR though and creating a DevTools feature flag system, so I'm going to take over this branch and finish out that part :smile: I think I'll make use of the flag for logging purposes anyway.

2020-10-12 14:29 UTC, bvaughn commented on packages/react-devtools-shared/src/hook.js
> +    if (enableConsolePatching && process.env.NODE_ENV !== 'test') {
Doest his actually work for you? Or does the Webpack-generated import statement just throw an error too (for the same reason as is mentioned in the inline comment:
```
        // Normally we could check "typeof patchConsole === 'function'",
        // but Webpack wraps imports with an object (e.g. _backend_console__WEBPACK_IMPORTED_MODULE_0__)
        // and the object itself will be undefined as well for the reasons mentioned above,
        // so we use try/catch instead.
```

When I tested it I see an error being thrown (and swallowed):
> ReferenceError: react_devtools_target_flags__WEBPACK_IMPORTED_MODULE_1__ is not defined

2020-10-12 14:35 UTC, bvaughn commented
Please hold off on additional commits.

2020-10-12 14:36 UTC, bl00mber commented
Thanks for the review! I've added a commit to rename TargetFlags to FeatureFlags, but I cannot yet confirm that this will work as intended - just waited for the confirmation to push forward before continuing working on the PR.

2020-10-12 15:11 UTC, bvaughn commented on packages/react-devtools-extensions/webpack.config.js
> +      __EXTENSION__: true,
This didn't need to be passed in as `process.NODE_ENV.TARGET`. It's only true for one of the Webpack config files (this one).

2020-10-12 15:11 UTC, bvaughn commented on packages/react-devtools-shared/src/hook.js
> +    if (!__EXTENSION__ && !__TEST__) {
This (boolean check) is what we needed to avoid runtime error.

2020-10-12 15:12 UTC, bvaughn approved these changes
Let's make sure CI is happy, then I'll merge.
Thanks for kicking this off!

2020-10-12 17:07 UTC, merged