Log and show error overlay for commit phase errors
facebook/react pull request #21723
Opened 2021-06-22 21:43 UTC by gaearon

Fixes https://github.com/facebook/react/issues/21712.
I regressed this in https://github.com/facebook/react/pull/21666.

The fix is to replicate the old behavior but only if we only catch something. This means we do it a bit later than it actually happens but assumptions about what gets logged are the same as before https://github.com/facebook/react/pull/21666.

2021-06-22 21:46 UTC, gaearon commented on packages/react-reconciler/src/ReactFiberWorkLoop.new.js
> +    invokeGuardedCallback(null, () => {
Note I could move it further down, e.g. only if it's caught by error boundary. Then boundary-less apps don't double-log the error in effects. However, they'd still double-log rendering errors. So I don't think this special case is worth it compared to having to remember why it's there and what it does.

2021-06-22 21:53 UTC, sebmarkbage reviewed
It's a little weird to put this here since it's tied to how each callsite in commitWork is structured. E.g. if some of them do use invokeGuardedCallback, they can't use this. Seems like it should be a different helper that lives in commitWork. E.g. call it before this capture function is called.

Do you need to call clearCaughtError after this so that it doesn't propagate to the next check for hasCaughtError?

2021-06-22 22:00 UTC, sebmarkbage requested changes
Pretty sure you need to call clearCaughtError or it'll error the next time something renders. Interesting that no test catches this because they probably don't do anything later and then clears the module state.

2021-06-22 23:29 UTC, gaearon commented
Seems like maybe including some tests in a PR is a good idea. Will do.

2021-06-24 14:43 UTC, bvaughn approved these changes
I think this looks good 👍🏼

2021-06-24 14:48 UTC, merged