Ignore meta content attribute escaping to prevent invalid URLs
facebook/react pull request #22041
Opened 2021-08-06 21:38 UTC by ihmpavel

## Summary

React automatically escapes HTML. Unfortunately for `<meta />` tags, escaping characters like `&` to `&amp;` could break URLs. There are a lot of issues and there is no easy solution (at least for raw `Next.js` hosted on Vercel). I know, escaping HTML is important, but it should not break URLs, which developers are not able to fix easily. 

This change is ignoring escaping `content` of `<meta />` attribute.

That means this tag
`<meta property='og:image' content='https://example.com?query1=one&query2=two' />` will not become `<meta property='og:image' content='https://example.com?query1=one&amp;query2=two' />`, but stays the same. (Encoding the URL will make it [fail](https://user-images.githubusercontent.com/3165635/46868650-52076f00-ce29-11e8-892f-cfbf924bba82.png))

Also it prevents duplicating escaping `<meta property='og:image' content='https://example.com?query1=one&amp;query2=two' />` to become `<meta property='og:image' content='https://example.com?query1=one&amp;amp;query2=two' />`.

Altough we have `dangerouslySetInnerHTML`, there is no such way to change it for attributes (eg `content` in `<meta />`), if it is not supported by `<React.Fragment />` for inserting `innerHTML`.

## Some related issues
https://github.com/facebook/react/issues/13838
https://github.com/vercel/next.js/issues/2006
https://github.com/garmeeh/next-seo/issues/678

## Test Plan

2021-08-07 07:51 UTC, crypt096 approved these changes

2021-09-06 19:59 UTC, gaearon commented
I might be missing something, but isn't this essentially introducing a security hole?

```js
let post = await db.getPost()

function App() {
  return (
    <...>
     <meta property='og:image' content={post.imageUrl} />
   </...>
  )
}

renderToString(<App />)
```

Now let's say `post.imageUrl` is actually

```
"'><script>alert("boom")</script><div class='"
```

wouldn't this let it through?

2021-09-06 20:01 UTC, gaearon requested changes
this looks like an XSS hole to me

2021-09-06 20:54 UTC, ihmpavel commented
Hi, thank you for the review. I have rechecked the implementation and it is XSS for sure. 

I was looking in the source code, but I could not find the solution I will be happy with. I do not want to introduce a security hole, but I want to fix the current problem. Sanitizing HTML is important, but sometimes it is not working as we would like to (https://github.com/vercel/next.js/issues/2006 or https://github.com/facebook/react/issues/13838). I was playing with some URL query parsers/servers and a lot of them could not get right params from sanitized url. (`?a=1&amp;b=2` is usually `{'a: 1, 'amp;b': 2}`).

Maybe `escapeHtml` function could accept as second parameter a boolean, which will decide not to encode `&` for `<meta content={} />` attribute? Or something like `dangerouslySetInnerHTML` for attributes? (`Next.JS` has it's own `<Head />` and we are not able to `dangerouslySetInnerHTML` in fragments; `<head dangerouslySetInnerHTML={...<meta content={} />...} />` is impossible to use.)
 
Let me know if you have any other idea which will not be something `hacky` as I have on my mind.

2021-09-06 22:28 UTC, gaearon commented
Yeah (I think) I understand the high-level problem, but this solution isn’t something that would work. Let’s discuss on the linked issue.

2021-09-06 22:28 UTC, closed without merging