devtools: Display StrictMode by default
facebook/react pull request #22201
Opened 2021-08-28 13:16 UTC by eps1lon

## Summary

Closes https://github.com/facebook/react/issues/21974

The "other" element type filter in devtools is currently in a weird spot (from a user and implementation perspective).

The "other" element type filter filters every component for which the computed devtools element type is `ElementTypeOtherOrUnknown`. The computed devtools element type is `ElementTypeOtherOrUnknown` for the following fiber tags:
1. `HostPortal`
2. `HostText`
3. `Fragment`
and the following symbols:
1. `CONCURRENT_MODE_NUMBER`
2. `CONCURRENT_MODE_SYMBOL_STRING`
3. `DEPRECATED_ASYNC_MODE_SYMBOL_STRING`
4. `STRICT_MODE_SYMBOL_STRING`
5. `STRICT_MODE_NUMBER`

See https://github.com/facebook/react/blob/8723e772b98d1a61aa0170981483c4da1e9237c5/packages/react-devtools-shared/src/backend/renderer.js#L965-L1016

However, the function responsible for determining whether a fiber should be filtered hides all of these types by default: https://github.com/facebook/react/blob/8723e772b98d1a61aa0170981483c4da1e9237c5/packages/react-devtools-shared/src/backend/renderer.js#L899-L928

So without this change, the "other" element type filter does not have any effect as far as I can tell. This change is really just about displaying `StrictMode` as reported by https://github.com/facebook/react/issues/21974. But, looking at the implementation, it seems like more types should be subject to the filter.

I see three paths forwards to avoid future confusion:
1. Split `ElementTypeOtherOrUnknown` into two new element types. One that will be filterable and one that's always hidden
2. Apply this fix to all `ElementTypeOtherOrUnknown`
2. Remove the "other" element filter i.e. https://github.com/facebook/react/issues/21974 is not a bug but a feature 

## Test Plan

- [x] Added tests for filtering `StrictMode`
- [x] Added `StrictMode` to parts of the shell
- [ ] CI green

2021-08-30 19:41 UTC, bvaughn requested changes
Hey @eps1lon! Thanks for the PR!

I don't think I agree with the spirit of #21974. There's more than one way for a tree to be in "strict mode". Using the `<StrictMode>` wrapper component is one such way, but passing an option to `createRoot()` is also a way.

The DevTools team has a few issues filed for addressing this in H2. We just haven't gotten around to it yet. I don't think I want to move forward with the approach outlined in this issue because I think it only addresses part of the issue.

I would be open to removing the "other" element filter type though, if it's actually not doing anything. If you'd like to update this PR to do that, or post a new PR, that'd be appreciated!

2021-08-30 20:10 UTC, eps1lon commented
> I would be open to removing the "other" element filter type though, if it's actually not doing anything. If you'd like to update this PR to do that, or post a new PR, that'd be appreciated!

I'll open a new one to keep the context visible.

 > I don't think I agree with the spirit of #21974. There's more than one way for a tree to be in "strict mode". Using the <StrictMode> wrapper component is one such way, but passing an option to createRoot() is also a way.

Makes sense. I was actually considering proposing an extra UI to see if a component is in StrictMode. Though I don't know how it should look.

2021-08-30 20:10 UTC, closed without merging

2021-08-31 06:46 UTC, eps1lon commented
> I would be open to removing the "other" element filter type though, if it's actually not doing anything. If you'd like to update this PR to do that, or post a new PR, that'd be appreciated!

On second thought, `ElementTypeOtherOrUnknown` is also the fallback type for `getElementTypeForFiber` and would apply to any future element type. 

Honestly, I don't think it matters all that much at the moment. Code is a bit odd at the moment but that's fine sometimes.

2021-08-31 08:04 UTC, ryota-murakami commented
I read nice discussion here, problem root is...
JSX is HTML like Syntax for React Element that VDOM object, so use for library internal setting like strict mode is not much better I think React is UI library therefore there is limitation of API design though.  

BTW how @eps1lon embed code section in markdown at first?  
this image one ⬇️

 
<img width="926" alt="Screen Shot 2021-08-31 at 17 01 44" src="https://user-images.githubusercontent.com/5501268/131466012-b598a001-5787-40d3-9de4-49327e06cc29.png">

2021-08-31 08:07 UTC, eps1lon commented
> BTW how @eps1lon embed code section in markdown at first?
> this image one

It's a link to source on GitHub which GitHub inlines: `https://github.com/facebook/react/blob/8723e772b98d1a61aa0170981483c4da1e9237c5/packages/react-devtools-shared/src/backend/renderer.js#L965-L1016`

2021-08-31 08:16 UTC, ryota-murakami commented
@eps1lon looks like this feature: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

2021-08-31 12:15 UTC, ryota-murakami commented
This code embed usually available from PR screen specific UI controls but also available from [another way](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet#linking-to-markdown).
Thank you for your response! @eps1lon