Delete useMutableSource implementation
facebook/react pull request #22292
Opened 2021-09-10 19:23 UTC by acdlite

useMutableSource is being replace with useSyncExternalStore.

Will wait to merge until after useSyncExternalStore is ready.

2021-09-10 20:28 UTC, bvaughn commented on packages/react-debug-tools/src/ReactDebugHooks.js
> -}
This shouldn't be deleted from debug hooks, should it? That affects DevTools, which has to support versions of React that had (unstable) `useMutableSource`.

2021-09-10 20:29 UTC, bvaughn requested changes
I think this is the first built-in hook that we've deleted, but I think we need to talk about about react-debug-tools handles such things going forward.

2021-09-10 20:39 UTC, acdlite commented
> This shouldn't be deleted from debug hooks, should it? That affects DevTools, which has to support versions of React that had (unstable) useMutableSource.

I assumed that since it was never stable, we don't have to support it indefinitely

2021-09-10 20:41 UTC, bvaughn commented
>> This shouldn't be deleted from debug hooks, should it? That affects DevTools, which has to support versions of React that had (unstable) useMutableSource.
>
> I assumed that since it was never stable, we don't have to support it indefinitely

I _think_ the cost of deleting this will be that DevTools throws an error if you ever inspect a component built with an alpha release that uses it.

Let's add this topic to Monday's sync?

2021-09-10 21:08 UTC, gaearon commented
Does Recoil use it?

2021-09-11 00:14 UTC, bvaughn commented
> Does Recoil use it?

Yes:
https://github.com/facebookexperimental/Recoil/blob/5783e70fd549acd8b5176b0d02e09eba9cbbd583/src/util/Recoil_mutableSource.js

https://github.com/facebookexperimental/Recoil/blob/888d1d0e27f9f1f4d6383e676b398487e142064b/src/hooks/Recoil_Hooks.js#L364

2021-09-14 13:33 UTC, windmaomao commented
> Does Recoil use it?

I remember you guys mentioned before seems `redux` uses it as well?

2021-09-14 13:42 UTC, acdlite commented
Recoil does use it but not before checking if the API exists

If they didn’t do that, Recoil would only work with experimental React builds.

2021-09-14 20:22 UTC, bvaughn approved these changes
Removing my objection here after discussion today.

2021-09-20 04:11 UTC, merged