Fix missing else in ReactDOMServerFormatConfig.js
facebook/react pull request #22431
Opened 2021-09-26 10:43 UTC by Hyperion101010

Removed else statement from ReactDOMServerFormatConfig.js
 Else statement was redundant since value is set anyways.
 Solves bug 22309.

## Summary
This PR removes redundant code from the ReactDOMServerFormatConfig.js file.
As discussed here [22309](https://github.com/facebook/react/issues/22309)

## How did you test this change?
Tested it using 
yarn prettier
yarn linc
yarn build and test

2021-09-27 06:16 UTC, akgupta0777 reviewed
The comment should be 
`//children is always a string`

2021-09-27 18:58 UTC, Hyperion101010 commented
@akgupta0777  fixed the comment and rebased branch.

2021-09-28 11:19 UTC, sbalikondwar commented
@justingrant any updates?

2021-09-28 19:17 UTC, justingrant requested changes
I suggested a few changes. Also, I'd suggest rebasing and squashing this into a single commit, because merge commits are discouraged in PRs. There are many ways to do this. Here's one way: 
```sh
git checkout fix-22309
# rewind your branch to before your first commit
# If you've made more commits, replace "4" with the number of commits in your PR
git reset HEAD~4
# stash all changes in those commits
git stash --include-untracked
# rebase this branch with the latest changes from upstream
git remote add upstream https://github.com/facebook/react.git
git pull upstream main
# stage your changes to the one file you changed
git checkout stash@{0} -- packages/react-dom/src/server/ReactDOMServerFormatConfig.js
# undo the checkout, leaving the changed file in your working directory
git reset
#
# NOW, MAKE YOUR ADDITIONAL EDITS FROM CODE REVIEW AND SAVE THEM
#
# commit changes you made
git add packages/react-dom/src/server/ReactDOMServerFormatConfig.js
git commit -m "remove unnecessary code"
# finally, force-push to your PR branch which will clean up history
git push -f
```

2021-09-28 20:04 UTC, Hyperion101010 commented on packages/react-dom/src/server/ReactDOMServerFormatConfig.js
>        if (__DEV__) {
Fixed

2021-09-28 20:05 UTC, Hyperion101010 commented on packages/react-dom/src/server/ReactDOMServerFormatConfig.js
>      }
Fixed

2021-09-28 20:05 UTC, Hyperion101010 commented on packages/react-dom/src/server/ReactDOMServerFormatConfig.js
> +    //children is always a string
Fixed

2021-09-28 20:13 UTC, Hyperion101010 commented on packages/react-dom/src/server/ReactDOMServerFormatConfig.js
>      }
Fixed

2021-09-28 20:18 UTC, Hyperion101010 commented
@justingrant all fixes are done, please review once.

2021-09-28 20:35 UTC, justingrant approved these changes
Looks good, thanks

2021-09-29 03:46 UTC, Hyperion101010 commented
What is the procedure to merge this PR? @justingrant

2021-09-29 04:52 UTC, justingrant commented
One of the maintainers will have to review it. There's 200+ open PRs so it might be a while. But this is a narrowly-scoped PR so it's unlikely to get stale soon. Someone should review & merge it sooner or later.

2021-10-01 07:43 UTC, crypt096 approved these changes

2021-10-01 15:24 UTC, Hyperion101010 commented
@crypt096  are you helping in maintaining reactjs?

2021-10-01 15:37 UTC, akgupta0777 commented
@bvaughn please review this PR.

2021-10-16 05:36 UTC, Hyperion101010 commented
@bvaughn any updates on this?

2024-04-17 16:04 UTC, closed without merging