[DevTools] Remove pointerEvents as a temporary fix for #24626
facebook/react pull request #24633
Opened 2022-05-28 19:20 UTC by mondaychen

## Summary

a temporary fix for #24626

## How did you test this change?

I created a chrome extension locally and loaded it in Chrome v104. The original issue is gone

https://user-images.githubusercontent.com/1001890/170839899-d36aafeb-61a7-4315-9cac-53e85afef271.mov

2022-05-29 03:29 UTC, lunaruan requested changes
This doesn't seem like the right fix here. The issue is that `requestAnimationFrame` isn't being called in extensions. Disabling `pointer-event: none` might break other things. I think probably the better fix here is to temporarily mock `requestAnimationFrame` with `setTimeout` in the extension instead. It won't be the exact same behavior as `requestAnimationFrame`, but it probably approximates it enough for now until Chrome fixes the bug.

2022-05-29 11:48 UTC, bvaughn commented
> I think probably the better fix here is to temporarily mock `requestAnimationFrame` with `setTimeout` in the extension instead.

This sounds right to me.

It was the same conclusion I came to after filing [CRbug 1241986](https://bugs.chromium.org/p/chromium/issues/detail?id=1241986). Although I thought I'd already added a `setTimeout` fallback for that case? I don't remember.

2022-05-29 20:36 UTC, mondaychen commented
I found https://github.com/bvaughn/react-window/issues/106 looks like the original implementation was `setTimeout`, but that was causing performance issues. I have concerns that if we mock `requestAnimationFrame` with `setTimeout` in the entire extension, it might cause more issues.

Based on what I've found in the bug repro, looks like `requestAnimationFrame` works fine if called in `panel.html`. Maybe  moving the rendering logic to panel.js from main.js will fix the problem, but I need to run some experiments to find out.

2022-05-31 02:53 UTC, lunaruan commented
> Based on what I've found in the bug repro, looks like `requestAnimationFrame` works fine if called in `panel.html`. Maybe  moving the rendering logic to panel.js from main.js will fix the problem, but I need to run some experiments to find out.

I think this also isn't the right fix. `main.js` is needed to access the [DevTools API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Extending_the_developer_tools). Yes, `setTimeout` sometimes makes the extension slower, but it's not common and only happens in inefficient apps that schedule tons of jobs. We have precedent in using `setTimeout` in both React and React Devtools, so I think it's okay.

Also, Chrome is currently in the process of looking at the bug, and this is more an interim fix while they fix the bug on their end. I think it's not worth the time to invest in heavy architecture refactors (that, realistically, most likely won't solve the issue) for this, and it's probably best to use `setTimeout`. It's not perfect; ideally we want to use `requestAnimationFrame`, but once Chrome fixes their bug we can switch back.

2022-05-31 16:56 UTC, mondaychen commented
@lunaruan updated with the mock

2022-05-31 17:52 UTC, lunaruan approved these changes
Looks good. Thanks for doing this!

2022-05-31 19:32 UTC, merged

2022-05-31 22:37 UTC, mondaychen commented on packages/react-devtools-extensions/src/main.js
> +  window.requestAnimationFrame = function(callback, element) {
That's a good idea! I'll submit a PR with that improvement tomorrow