Post-process build files for React Native to add generated signature and @nolint
facebook/react pull request #26616
Opened 2023-04-13 13:25 UTC by rubennorte

## Summary

We're enabling a new mechanism to synchronize build files from `react` to `react-native`. That new mechanism doesn't post-process files, so we need to add that post-processing somewhere. This PR does that when generating the files in the first place, so the generated files in the `build` directory are ready to be committed in the `react-native` repository directly.

This makes use of `signedsource` to avoid direct modifications of these files in the `react-native` repository, as well as `@noformat` and `@nolint` to prevent unactionable CI failures in that repository.

## How did you test this change?

Generated build files for `react-native` before and after this change:
```
node ./scripts/rollup/build-all-release-channels.js react-native
```

Checked new contents. Relevant changes:

```diff
diff --color -r build-before/react-native/implementations/ReactFabric-dev.fb.js build-after/react-native/implementations/ReactFabric-dev.fb.js
10c10
<  * @generated
---
>  * @generated SignedSource<<03cef14e77b8250b567dfdf3b066085e>>
diff --color -r build-before/react-native/implementations/ReactFabric-dev.js build-after/react-native/implementations/ReactFabric-dev.js
11c11
<  * @generated
---
>  * @generated SignedSource<<e39eed38a363846ca9ee9b59a225683c>>
diff --color -r build-before/react-native/implementations/ReactFabric-prod.fb.js build-after/react-native/implementations/ReactFabric-prod.fb.js
10c10
<  * @generated
---
>  * @generated SignedSource<<f65efcd6a469d5f6fef1ce647e5ec09a>>
diff --color -r build-before/react-native/implementations/ReactFabric-prod.js build-after/react-native/implementations/ReactFabric-prod.js
11c11
<  * @generated
---
>  * @generated SignedSource<<cdd582aa889b1054b2c5faf412622b18>>
diff --color -r build-before/react-native/implementations/ReactFabric-profiling.fb.js build-after/react-native/implementations/ReactFabric-profiling.fb.js
10c10
<  * @generated
---
>  * @generated SignedSource<<81e74849b24f104882bd298f062be0fa>>
diff --color -r build-before/react-native/implementations/ReactFabric-profiling.js build-after/react-native/implementations/ReactFabric-profiling.js
11c11
<  * @generated
---
>  * @generated SignedSource<<c050b7fa1453dc21ac1c5b98146210a8>>
diff --color -r build-before/react-native/implementations/ReactNativeRenderer-dev.fb.js build-after/react-native/implementations/ReactNativeRenderer-dev.fb.js
10c10
<  * @generated
---
>  * @generated SignedSource<<9c03464b489b41c06a065aeba8619263>>
diff --color -r build-before/react-native/implementations/ReactNativeRenderer-dev.js build-after/react-native/implementations/ReactNativeRenderer-dev.js
11c11
<  * @generated
---
>  * @generated SignedSource<<18b34c037544949dcf9b28f945921ba8>>
diff --color -r build-before/react-native/implementations/ReactNativeRenderer-prod.fb.js build-after/react-native/implementations/ReactNativeRenderer-prod.fb.js
10c10
<  * @generated
---
>  * @generated SignedSource<<592e9654c584d1da523378b119bd8bd7>>
diff --color -r build-before/react-native/implementations/ReactNativeRenderer-prod.js build-after/react-native/implementations/ReactNativeRenderer-prod.js
11c11
<  * @generated
---
>  * @generated SignedSource<<91c894db99e2d76f8a32708ad6ad1bde>>
diff --color -r build-before/react-native/implementations/ReactNativeRenderer-profiling.fb.js build-after/react-native/implementations/ReactNativeRenderer-profiling.fb.js
10c10
<  * @generated
---
>  * @generated SignedSource<<5ce378a9216ea747d91b208b9fd1ebd5>>
diff --color -r build-before/react-native/implementations/ReactNativeRenderer-profiling.js build-after/react-native/implementations/ReactNativeRenderer-profiling.js
11c11
<  * @generated
---
>  * @generated SignedSource<<1c7564f446ee83142976035b2884dcfd>>
diff --color -r build-before/react-native/shims/ReactFabric.js build-after/react-native/shims/ReactFabric.js
7c7
<  * @format
---
>  * @noformat
8a9,10
>  * @nolint
>  * @generated SignedSource<<cece19ddbec9f287c995721f49c68977>>
diff --color -r build-before/react-native/shims/ReactFeatureFlags.js build-after/react-native/shims/ReactFeatureFlags.js
7c7
<  * @format
---
>  * @noformat
8a9,10
>  * @nolint
>  * @generated SignedSource<<2881c8e89ef0f73f4cf6612cb518b197>>
diff --color -r build-before/react-native/shims/ReactNative.js build-after/react-native/shims/ReactNative.js
7c7
<  * @format
---
>  * @noformat
8a9,10
>  * @nolint
>  * @generated SignedSource<<0debd6e5a17dc037cb4661315a886de6>>
diff --color -r build-before/react-native/shims/ReactNativeTypes.js build-after/react-native/shims/ReactNativeTypes.js
7c7
<  * @format
---
>  * @noformat
8a9,10
>  * @nolint
>  * @generated SignedSource<<652b117c94307244bcf5e4af18928903>>
diff --color -r build-before/react-native/shims/ReactNativeViewConfigRegistry.js build-after/react-native/shims/ReactNativeViewConfigRegistry.js
7c7
<  * @format
---
>  * @noformat
8a9,10
>  * @nolint
>  * @generated SignedSource<<ce82e8957367bee7d11379ab88e3f7c5>>
diff --color -r build-before/react-native/shims/createReactNativeComponentClass.js build-after/react-native/shims/createReactNativeComponentClass.js
7c7
<  * @format
---
>  * @noformat
8a9,10
>  * @nolint
>  * @generated SignedSource<<ede54ac2fa1b9a09e234cdf098048989>>
```

2023-04-13 13:30 UTC, rickhanlonii requested changes
If I understand correctly, this is changing the build artifacts that are generated by `yarn build`? If so, I think the right place to do this is in the diff train workflow, when we sync to the Meta repo. That way, Meta specific needs are not leaked into the build outputs, and stay in the sync pipeline.

2023-04-13 13:37 UTC, rubennorte commented
>  If I understand correctly, this is changing the build artifacts that are generated by yarn build? If so, I think the right place to do this is in the diff train workflow, when we sync to the Meta repo. That way, Meta specific needs are not leaked into the build outputs, and stay in the sync pipeline.

@rickhanlonii these generated files are already `react-native` specific, and I'm just adjusting the build process to generate them the way we're going to consume them in `react-native`. What part did you think it didn't belong here? Adding `@nolint` or replacing `@generated` with its signed counterpart?

2023-04-13 15:14 UTC, rickhanlonii commented
Both, in my mind. The sync script used to add that during the sync, so the equivalent layer of that is the diff train sync script. Concretely, we shouldn't see the meta specific comments in the `https://react-builds.vercel.app/` tool, or take the extra time to generate the shas during `yarn build`, or need to maintain this if we make changes to the build scripts.

2023-04-13 18:14 UTC, rickhanlonii approved these changes

2023-04-14 09:42 UTC, merged

2023-04-24 18:56 UTC, markerikson commented
This PR seems to have broken my ability to build React locally :(

Context:

- I have a local clone of the React repo that I've been using to work on #26446 
- We also have a fork over the whole repo over at https://github.com/replayio/react , where I've been maintaining a branch that modifies the React DevTools backend for use with Replay.io's React DevTools integration

I just tried to merge `main` into these branches to pick up the latest changes.  #26446 builds okay in CI.  But, any build that includes these changes (whether I'm building straight from `main` or my sourcemaps branch + `main`) fails with:

```
Error: SignedSource.signFile(...): Cannot sign file without token: <<SignedSource::*O*zOeWoEQle#+L!plEphiEmie@IsG>>
    at Object.<anonymous> (C:\Projects\react\node_modules\signedsource\index.js:20:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Projects\react\scripts\rollup\packaging.js:18:37)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
```

This happens with both `yarn build` and `yarn build-for-devtools`.

It appears that it's coming from these steps in `scripts/rollup/packaging.js`:

```js
async function copyRNShims() {
  await asyncCopyTo(
    `${__dirname}/shims/react-native`,
    'build/react-native/shims'
  );
  await asyncCopyTo(
    require.resolve('react-native-renderer/src/ReactNativeTypes.js'),
    'build/react-native/shims/ReactNativeTypes.js'
  );
  processGenerated('build/react-native/shims');
}

function processGenerated(directory) {
  const files = readdirSync(directory)
    .filter(dir => dir.endsWith('.js'))
    .map(file => path.join(directory, file));

  files.forEach(file => {
    const originalContents = readFileSync(file, 'utf8');
    const contents = originalContents
      // Replace {@}format with {@}noformat
      .replace(/(\n\s*\*\s*)@format\b.*(\n)/, '$1@noformat$2')
      // Add {@}nolint and {@}generated
      .replace(' */\n', ` * @nolint\n * ${getSigningToken()}\n */\n`);
    const signedContents = signFile(contents);
    writeFileSync(file, signedContents, 'utf8');
  });
}
```

and specifically from trying to process `build\react-native\shims\createReactNativeComponentClass.js`:

```js
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @format
 * @flow strict-local
 */

'use strict';

import {ReactNativeViewConfigRegistry} from 'react-native/Libraries/ReactPrivate/ReactNativePrivateInterface';
import {type ViewConfig} from './ReactNativeTypes';

const {register} = ReactNativeViewConfigRegistry;

/**
 * Creates a renderable ReactNative host component.
 * Use this method for view configs that are loaded from UIManager.
 * Use createReactNativeComponentClass() for view configs defined within JavaScript.
 *
 * @param {string} config iOS View configuration.
 * @private
 */
const createReactNativeComponentClass = function (
  name: string,
  callback: () => ViewConfig,
): string {
  return register(name, callback);
};

module.exports = createReactNativeComponentClass;
```

Given that the shim file _doesn't_ have a token-related string in it, I think the error sort of makes sense conceptually.

I'm not sure what would be missing or different on my end that would make this fail, or why no one else seems to have reported it yet.

Any suggestions on getting the build process working for me again?