Fix escaping in ReactDOMInput code
facebook/react pull request #26630
Opened 2023-04-15 00:42 UTC by sophiebits

JSON.stringify isn't the right thing here. Luckily this doesn't look to have any security impact.

2023-04-15 00:43 UTC, sebmarkbage approved these changes

2023-04-15 04:47 UTC, gnoff commented on packages/react-dom-bindings/src/client/escapeSelectorAttributeValueInsideDoubleQuotes.js
> +    ch => '\\' + ch.charCodeAt(0).toString(16),
Yeah that seems right

2023-04-15 04:49 UTC, gnoff approved these changes

2023-04-15 21:12 UTC, gnoff requested changes
Hmm I thought the space would be consumed by the escape sequence. The selector can’t change, we rely on an invariant that hrefs for float style tags and style sheet link tags do not have spaces in them. This is because we coalesce multiple style tags into a single flushed tag and use this space separated selector to look for a match.


I wouldn’t have thought the escape change would affect this, shouldn’t the new space be consumed?

2023-04-15 21:16 UTC, sophiebits commented
(Thanks for looking – was going to tag you on Monday before merging.)

Yes. It's a bug in the selector library used by jsdom that filed an issue for this morning: https://github.com/dperini/nwsapi/issues/84. I confirmed that `~=` with an escape works correctly in Blink, WebKit, and Gecko. I think this new code is correct since I'm still using `data-href~=` but lmk if you don't think so.

2023-04-21 02:40 UTC, sophiebits commented
@gnoff thoughts?

2023-04-24 16:44 UTC, gnoff approved these changes
I'm sorry I lost the thread. You're right (of course :))

I would like to refactor against the notion of key <> selector now that they aren't really one to one. But agree this does preserver the style selector semantics

2023-04-24 17:33 UTC, sophiebits commented
no worries! thanks for looking

2023-04-24 17:33 UTC, merged