Split Update flag into a mutation and effect flag
facebook/react pull request #27533
Opened 2023-10-17 14:08 UTC by kassens

The `Update` flag was overloaded to mean that there's "work to do during the commit phase". On the one side that was updates to host components. On the other side that meant running effects.

The flag was also used in persistent mode to trigger cloning the immutable view hierarchy to perform the updates. When the flag was only used to indicate calling effects, this meant needlessly cloning the subtree.

Here we *start* splitting up the flag into 2. In the transition phase we set both flags in some places, but most likey every location should only set or check one of the flags.

2023-10-17 15:41 UTC, javache commented on packages/react-native-renderer/src/__tests__/ReactFabric-test.internal.js
> +      // Same thing happens with `ref` and `useImperativeHandle`
Worth testing that ref / useImperativeHandle now pass this test too?

2023-10-17 16:14 UTC, acdlite requested changes
I think a better overall approach would be to add a flag that represents something that has been cloned. Call it `Cloned` or something.

It would only be set in persistent mode, not mutation mode, and it would accompany any call to `cloneInstance`, `cloneText`, et al.

Then you can update this function to check for Cloned instead of MutationMask:

https://github.com/facebook/react/blob/9abf6fa31cd7ff4c6e54de75950620e203c59ebf/packages/react-reconciler/src/ReactFiberCompleteWork.js#L204-L205

I think this would be simpler because it's less likely the meanings of the flags will get overloaded again.

2023-10-25 15:52 UTC, kassens commented
@acdlite Our thought for further splitting of this flag was that we could potentially safe some traversal down if only host components are updated, but other update effects aren't in place. Is that assumption wrong and we basically always have the (non-clone) effect set if there would be a "cloned" flag set?

2023-11-09 17:01 UTC, closed without merging

2023-11-09 17:01 UTC, kassens commented
Superseded by #27647