enable isInputPending in Scheduler
facebook/react pull request #27826
Opened 2023-12-11 19:26 UTC by noahlemen

## Summary

This has been enabled at Meta for some time, but it looks like the changes were never published here. Enables isInputPending at a `maxYieldMs` of 10ms. Removes `enableIsInputPendingContinuous` flag and its corresponding yield interval, as we ended up landing on a configuration where it never got used.

## How did you test this change?
`yarn test-www`

2023-12-11 19:28 UTC, noahlemen commented
ah, need to update Scheduler tests

2023-12-11 19:36 UTC, josephsavona approved these changes

2023-12-13 16:23 UTC, rickhanlonii requested changes
What about browsers that don't support isInputPending (basically all non-chromium browsers)? Those should stay 5ms.

2023-12-13 16:34 UTC, noahlemen commented
@rickhanlonii yeah, this is already implemented with feature detection: https://github.com/facebook/react/blob/noahlemen-iip-scheduler/packages/scheduler/src/forks/Scheduler.js#L104-L111

it will continue with the 5ms frame interval if its not defined: https://github.com/facebook/react/blob/noahlemen-iip-scheduler/packages/scheduler/src/forks/Scheduler.js#L472-L503

2024-02-20 17:23 UTC, closed without merging