Export unstable_useMemoCache from ReactSharedSubset
facebook/react pull request #27829
Opened 2023-12-12 16:58 UTC by alunyov

Expose `unstable_useMemoCache` on `ReactSharedSubset` in cases where forget is applied to RSC.

2023-12-13 19:06 UTC, josephsavona approved these changes
Have you tested that this will work? This hook attaches to the fiber node so i'm not sure if this would even work in RSCs.

2023-12-13 19:16 UTC, sebmarkbage commented
Hm. I think we probably shouldn't include this because we don't plan on running it in RSC (nor SSR).

The runtime can't handle the memoization and we're actively trying to get rid of the multiple passes in SSR.

Since the RSC graph must compile separately, it should also be possible to exclude Forget (or apply an RSC specific compiler to that graph).

2023-12-13 19:18 UTC, sebmarkbage requested changes
At the very least this shouldn't be exposed in the stable builds and since this entry point isn't forked yet, you need to first create a `react.shared-subset.stable.js` fork that excludes it.

2023-12-13 19:28 UTC, alunyov commented
Thanks, @sebmarkbage!

Yeah, we have a forked version already, I'll move it there for now. 

> The runtime can't handle the memoization

Can you clarify that a little bit? Currently we have `useMemo` for example in this shared subset, does this work? Or it's a different memoization?

2023-12-13 19:31 UTC, alunyov commented
> Have you tested that this will work? This hook attaches to the fiber node so i'm not sure if this would even work in RSCs.

@josephsavona tested internally, it works.

2023-12-13 19:58 UTC, alunyov commented
> it should also be possible to exclude Forget

Yeah, I think this is also possible. 

@sebmarkbage but still want to clarify the state of memoization in RSC? IIUC, We still have multiple "re-renderers" of RSC?For example, when the promises for pending tasks are resolved, should we/can we rely on memoization for the components that gets "re-rendered" in this case?

2023-12-14 17:37 UTC, sebmarkbage commented
> For example, when the promises for pending tasks are resolved, should we/can we rely on memoization for the components that gets "re-rendered" in this case?

Ideally this would compile `use()` to generators instead since there's no new input that can come in.

However, this is also a very unusual case for RSC since you typically wouldn't use a "Shared" component with `use()`, you would use an async function. So it wouldn't be worth including fiber tracing for it since it's exceedingly rare to have a Shared component that uses `use()` over an async function.

I guess maybe Relay would be a counter argument but that opens a question of if there's really two worlds of RSC then.

2023-12-14 17:37 UTC, sebmarkbage commented
The reason `useMemo` is there at all is because we can't change the code if it's a shared components where the memoization might matter on the client but it's really a noop.

2023-12-14 21:25 UTC, alunyov commented
Thanks @sebmarkbage @josephsavona for review and feedback. I think I won't be adding change, I've already excluded RSC from Forget, so we don't need this.

2023-12-14 21:25 UTC, closed without merging