Deprecate `act` from `react-dom/test-utils` in favor of act from `react`
facebook/react pull request #28597
Opened 2024-03-20 18:18 UTC by eps1lon

Stacked on https://github.com/facebook/react/pull/28541/

## Summary

Use `React.act` instead:
```diff
-import {act} from 'react-dom/test-utils'
+import {act} from 'react'
```

## How did you test this change?

- using `React.act` now instead of `ReactDOMTestUtils` when testing the public `act`
- added test for the new warning

2024-03-23 20:30 UTC, rickhanlonii requested changes

2024-03-23 20:30 UTC, rickhanlonii commented on packages/react-dom/src/__tests__/ReactTestUtils-test.js
> +        'For testing React, we recommend React Testing Library instead: https://testing-library.com/docs/react-testing-library/intro.',
Similar to the react-test-renderer warning, I don't think we should hard code the recommendations into the error message, instead something like:

> `isDOMComponent` was removed from `react-dom/test-utils`. See https://react.dev/warnings/react-test-renderer for more info.

2024-03-23 20:30 UTC, rickhanlonii commented on packages/react-dom/src/__tests__/ReactTestUtils-test.js
> +        'For testing React, we recommend React Testing Library instead: https://testing-library.com/docs/react-testing-library/intro.',
Ditto for the other warning messages added here.

2024-03-23 20:30 UTC, rickhanlonii commented on packages/react-dom/src/__tests__/ReactTestUtils-test.js
> +        'For testing React, we recommend React Testing Library instead: https://testing-library.com/docs/react-testing-library/intro.',
And we can update that warning page with info on which methods were removed, and why we removed them.

2024-03-27 13:57 UTC, jackpope approved these changes

2024-03-27 15:08 UTC, eps1lon commented on packages/react-dom/src/__tests__/ReactTestUtilsAct-test.js
> +describe('React.act()', () => {
```suggestion
describe('ReactTestUtils.act()', () => {
```

name was fine. I thought it spelled `ReactDOMTestUtils `

2024-03-27 15:11 UTC, eps1lon commented on packages/react-dom/src/__tests__/ReactTestUtilsAct-test.js
> +describe('React.act()', () => {
React.act() is probably clearer even though it no longer matches the filename. Just don't want to rename to make blaming easier.

2024-03-27 15:28 UTC, merged