Cleanup enableUseRefAccessWarning flag
facebook/react pull request #28699
Opened 2024-04-01 17:15 UTC by kassens

Cleanup enableUseRefAccessWarning flag

I don't think this flag has a path forward in the current implementation. The detection by stack trace is too brittle to detect the lazy initialization pattern reliably (see e.g. some internal tests that expect the warning because they use lazy intialization, but a slightly different pattern then the expected pattern.

I think a new version of this could be to fully ban ref access during render with an alternative API for the exceptional cases that today require ref access during render.

2024-04-01 18:58 UTC, rickhanlonii requested changes
I think we still want this?

2024-04-01 19:26 UTC, kassens commented on packages/use-sync-external-store/src/__tests__/useSyncExternalStoreShared-test.js
> -  // @gate !(enableUseRefAccessWarning && __DEV__)
See example this was opted out, because it supposedly uses the "lazy ref init pattern", so the checks that try to allow that are failing here.

2024-04-01 20:35 UTC, kassens commented
The feature flag was basically untouched since it was added and didn't have an owner in years.

I briefly tried to enable it, but the detection was way to unreliable and I don't see a path forward for the current approach.

2024-04-03 17:34 UTC, rickhanlonii approved these changes
Ok let's remove

2024-04-03 17:35 UTC, merged