[Flight][Fizz] ping work within current task
facebook/react pull request #28894
Opened 2024-04-23 05:23 UTC by gnoff

Fizz and Flight both currently have a work schedule that enqueues tasks for retrying in a new macrotask. however it means that any given render will be split across multiple tasks even if any thenables that suspend are available within a microtask. This PR updates the ping mechanism for both renderers to schedule retry work on the microtask queue.

As we've run into many times in React this is another instance where being able to schedule a microtask to run at the end of the queue would be ideal since we can optimize flushing better.

2024-04-23 05:32 UTC, Jesus-Rojas reviewed
Good job !!

2024-04-23 05:32 UTC, Jesus-Rojas commented on packages/react-dom/src/__tests__/ReactDOMFizzServerNode-test.js
> +      console.log('rendering');
Remove 

```suggestion
      console.log('rendering');
```

2024-04-23 05:32 UTC, Jesus-Rojas commented on packages/react-dom/src/__tests__/ReactDOMFizzServerNode-test.js
> +      writable.on('error', pl => {
Param not used

```suggestion
      writable.on('error', () => {
```

2024-04-23 07:09 UTC, sebmarkbage requested changes
This is problematic because there can be many macro tasks already scheduled on the queue from the I/O threads. The goal of the macro task is to exhaust as many of those as possible to be able to render through as much as possible.

This was more efficient when we were able to synchronously render through things that had already loaded in RSC. We still can do that for instrumented promises such as those coming from a Flight stream. I.e. most Fizz work. But ideally we could also do it with more preloads and such with Flight too.

2024-04-25 01:07 UTC, gnoff commented
closing in favor of https://github.com/facebook/react/pull/28907

2024-04-25 01:07 UTC, closed without merging