Fix react-compiler entrypoint for react-server
facebook/react pull request #29057
Opened 2024-05-15 00:58 UTC by lubieowoce

## Summary

Fix the `/react-compiler` entrypoint when imported under "react-server".
This adds a new `react-compiler-runtime.react-server` entrypoint. We need a separate "react-server" build, because otherwise the compiler runtime attempts to use `__CLIENT_INTERNALS` even under the "react-server" condition, and crashes before it can even e.g. error about a missing dispatcher.

AFAICT this is because in a server environment, we need `shared/ReactSharedInternals` to be [rewritten to use the server internals instead](https://github.com/facebook/react/blob/3f848028c67235441a4149c4885245cc49edcb40/scripts/rollup/forks.js#L68-L70). If no "react-server" condition is passed to the build, it'll default to `ReactSharedInternalsClient`, so we need an additional bundle.

## How did you test this change?

Not sure what the best way to test this is, but this previously crashed with `"Cannot read properties of undefined (reading 'H')"` (because it was attempting to access client internals)

```
$ yarn build; rm -rf node_modules/react
$ NODE_PATH="$PWD/build/oss-stable" node --conditions=react-server -p 'require("react/compiler-runtime").c()'
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

2024-05-15 02:12 UTC, lubieowoce commented on packages/react/src/ReactCompilerRuntimeServer.js
Alternatively, this could be a stub file like
```js
throw new Error("The React compiler does not support Server Components.");
```
because AFAIK RSC's are not currently intended to be processed by the compiler. But the dispatcher does have a (dummy) `useMemoCache` implementation, so i'm not sure what the right call here is

2024-05-15 03:34 UTC, sebmarkbage requested changes
A throwing stub is the way.

https://github.com/facebook/react/blob/main/packages/react-dom/npm/server.react-server.js#L3-L5

This export was previously on the main `react` runtime and that was the reason we couldn't do that. However, if the React Compiler starts supporting some modes in the RSC mode such as optimizing RSC rendering this wouldn't work again.

We have as a principle that we should follow ESM so that there can be an early compiler error if an ESM export is missing. This can catch errors earlier without having to run some code. Erroring early is more important than error with a nice message. It also provides the option to conditionally check for the existence of a method if you import it in the other way that it doesn't early error.

In this case it doesn't harm adding the throw in the module initializer but we might have to drop that once we start having react-compiler support for RSC things. At the end of the day, whoever is configuring an advanced set up like a compiler isn't our main target for nice error messages so it's not the end of the world.

2024-05-15 03:35 UTC, sebmarkbage commented on packages/react/src/ReactCompilerRuntimeServer.js
> But also, the Flight dispatcher does have a stub useMemoCache implementation

We should remove it.

2024-05-15 10:03 UTC, lubieowoce commented
@sebmarkbage Happy to change it, but i see one argument for making this a noop instead of an error-stub that I'd like us to consider first

If an NPM dependency exports a universal (server + client) component, and started compiling its code with the compiler (IIRC shipping compiled code is the recommendation?), then the error-stub would make importing that component in a server context no longer possible, because it'd instantly throw. Fixing the errors would then require one of these:

- The package author needs to fork their code based on `"react-server"` and only compile the client part. This complicates their build process -- code that was previously universal now needs to be forked, and the author needs to understand that + use tooling capable of building the package like that, which is an added ecosystem burden

- The package consumer would need to add to wrap the component in a `"use client"; export { PreviouslyUniversal } from "compiled-package"` wrapper to stop the errors. This may not be intuitive, and could lead to client-ifying the code unnecessarily

I definitely understand the desire to be strict here, but I feel like this could end up causing unnecessary ecosystem churn. So maybe it's worth being more lenient and no-oping instead?

2024-05-16 02:15 UTC, sebmarkbage commented
That's expected though because compiled code might not work with RSC. There's no guarantee that the compiled output would run with any kind of noop memoization and it's not prepared for what we have planned for the JSX runtime inside the RSC layer. The "RSC Compiler" would not work for client code.

So by breaking it now we're ensuring that it keeps working in the contexts that it used to work.

The solution for a library that wants to use everything is a more complex build set up but that's the case regardless.

2024-05-16 02:17 UTC, sebmarkbage commented
More than that, I don't think the compiler story for SSR is fully figured out. E.g. we should really have an SSR compiler that can produce more "string concat" style optimizations and we plan on it excluding things like useEffect and inlining useState.

The React Compiler as is now really shouldn't be applied to the SSR layer so if published to npm with the compiled output it really shouldn't be used with SSR. That story doesn't quite make sense yet.

2024-05-16 09:57 UTC, lubieowoce commented
Just found another issue:
https://github.com/facebook/react/blob/149b917c8a4022aeaa170c4fb826107dd2333c68/compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Imports.ts#L96-L121

So, if the file contains `import { ... } from 'react'`, the compiler will add `useMemoCache as _c` to that.
Otherwise it'll add a new `import { c as _c } from 'react/compiler-runtime'`.

So If we turn this into a throwing stub, the former would "work" (because of the dummy `useMemoCache` in the server dispatcher), but the latter would throw. So I guess we also have to remove `useMemoCache` from the server entrypoint to be consistent.

2024-05-16 10:04 UTC, lubieowoce commented
CC @poteto @josephsavona @gsathya thoughts?

2024-05-17 17:58 UTC, josephsavona commented
Thanks for posting this. I think we need to discuss the path forward for React Compiler and SSR/RSC a bit more before proceeding.

2024-08-22 19:05 UTC, closed without merging