Enable suspenseCallback on React Native
facebook/react pull request #29210
Opened 2024-05-22 14:54 UTC by bgirard

## Summary

suspenseCallback feature has proved to be useful for FB Web. Let's look at enabling the feature for the React Native build.

## How did you test this change?

Will sync the react changes with a React Native build and will verify that performance logging is correctly notified of suspense promises during the suspense callback.

2024-05-22 15:47 UTC, rickhanlonii requested changes
Let's discuss more, I'm not sure if we want to expand usage of this feature until we know for sure it makes sense and has a path to making it to open source.

2024-08-22 18:03 UTC, rickhanlonii approved these changes

2024-08-22 20:42 UTC, poteto approved these changes

2024-08-22 20:42 UTC, poteto commented on patch
oops

2024-08-22 20:43 UTC, bgirard commented on patch
yup lol, my git is rusty. Fixing it now.

2024-08-27 02:06 UTC, merged