Adds option to resolve raw text support from view configs
facebook/react pull request #29872
Opened 2024-06-12 15:58 UTC by rozele

## Summary

Hardcoding this set of host component names isn't great. It means that, outside of core components like <Text> and <TextInput> in react-native, nothing can support string children in React Native. This hardcoded list also prevents out-of-tree platforms (e.g., react-native-windows) from having control over their own host component names and behaviors. To have feature parity with iOS and Android, an out-of-tree platform would have to name it's host component for TextInput either `AndroidTextInput`, `RCTSinglelineTextInput` or `RCTMultilineTextInput`, and it would preclude out-of-tree platforms from creating even more host platform component options for things like TextInput with `secureTextEntry={true}` (for password entry), or different components supporting rich text vs. plain text features.

Additionally, having a hardcoded set of host component names for allowing string children prevents any 3rd party package from defining their own Text-like component. There is no reason the core package for React Native should hold the only keys to creating this type of component.

Moving to reading these values from the host platform view config solves both problems. This change adds a feature flag to enable just that.

## How did you test this change?

Copied these changes into react-native-windows, set the feature flag to true, added the supportsRawText flag to the view config for WindowsTextInput, and confirmed it can accept raw text children.

2024-06-12 16:07 UTC, motiz88 commented on packages/react-native-renderer/src/ReactFiberConfigFabric.js
> +    ? getViewConfigForType(type).supportsRawText
Probably want to coalesce this to `false` if it's not normalised elsewhere.

```suggestion
    ? getViewConfigForType(type).supportsRawText ?? false
```

2024-06-12 16:07 UTC, motiz88 commented on packages/react-native-renderer/src/ReactNativeTypes.js
> +  supportsRawText?: boolean,
Looks like this should also be added to the `ViewConfig` type - possibly as optional for now, then required when we've updated React Native to always supply it.

2024-06-19 11:37 UTC, javache submitted a review, later dismissed
Could we make this change incremental? Eg check for `supportsRawText`, and if not set or false, check the existing list of component names? That way we have to do less juggling to make this change atomic.

2024-06-19 13:20 UTC, rickhanlonii requested changes
Can you add tests? I know that this just updates the types, but there should be some sort of tests for this behavior before we start implementing it. And the existing tests that are there are currently passing, but should fail without the changes @javache mentioned.

Here's where I would add them:  https://github.com/facebook/react/blob/1940cb27b260c2eab79c76763d1151ba18353ff8/packages/react-native-renderer/src/__tests__/ReactFabric-test.internal.js#L583

2024-06-20 18:18 UTC, rozele commented
> Could we make this change incremental? Eg check for `supportsRawText`, and if not set or false, check the existing list of component names? That way we have to do less juggling to make this change atomic.

Not seeing the value in this, it's just as easy to:
1. expose the types in React
2. make the change in RN to use the types
3. Switch to using ViewConfig in React

As it is to:
1. Expose the types and using ViewConfig with fallback in React
2. Make the change in RN to use the types
3. Remove the fallback list in React

2024-06-20 18:21 UTC, rozele commented
@rickhanlonii if we are just adding types in this change, there's not really anything to test. The subsequent change after RN is updated to consume the new types will need to update the existing tests, which appear to have sufficient coverage.

2024-06-20 18:35 UTC, rickhanlonii commented
> here's not really anything to test

Yeah ok sure, we can add tests when we do step 3 to actually consume the prop in React. If you're going this route though, it would be easier to just add the props to the config with a FlowFixMe and remove the FlowFixMe after the behavior change lands. 

Then you could add the type, the behavior, and the tests all in one React PR.

2024-06-20 18:35 UTC, rickhanlonii approved these changes

2024-07-11 16:47 UTC, merged