[compiler] Enable sourceMaps in tsconfig
facebook/react pull request #30064
Opened 2024-06-24 15:15 UTC by gsathya

With this, we can set a `debugger` breakpoint and we'll break into the source code when running tests with snap. Without this, we'd break into the transpiled js code.

2024-06-24 17:39 UTC, josephsavona approved these changes
nice!

2024-06-24 20:18 UTC, poteto requested changes
Would you mind seeing if you can add this option to the virtual tsconfig instead?: https://github.com/facebook/react/blob/main/compiler/packages/snap/src/runner-watch.ts#L30

The downside of changing tsconfig directly is that it affects our build and generates extra files that will be included in npm. And if we can help it I'd rather not have any source maps in there because it's unnecessary for a build-time only module plus bloats the package size a bit.

2024-06-25 11:17 UTC, gsathya commented
> Would you mind seeing if you can add this option to the virtual tsconfig instead?

Done

2024-06-25 13:01 UTC, poteto approved these changes
thank you!! 🤍🤍🤍

2024-06-25 16:01 UTC, merged