[compiler] use reactiveConditionHelper to reduce size
facebook/react pull request #30171
Opened 2024-07-01 16:19 UTC by GrinZero

I found that when studying react compiler, the compiler always compiles `scope` into very similar conditional comparison code blocks. So I am thinking about whether it is possible to extract these similar code blocks into a common function, which may help reduce the code volume of large-scale projects.

## Overview

This PR introduces a new runtime, which I call conditionHelper. It organizes reusable logic in the scope and separates it into common functions to reduce the volume of compiled code. Although this is only an initial implementation and there are still testing and other tasks to be completed, it has a certain positive effect on reducing the volume of compiled code.

## Demo

Modifying the babel option allows you to experience helpers, like:
```js
...
  babel: {
    plugins: [
      [
        "babel-plugin-react-compiler",
        {
          environment: {
            enableReactiveScopeConditionHelper: true,
          },
        },
      ],
    ],
  },
...
```

And run `build` or `dev`:
<img width="687" alt="image" src="https://github.com/facebook/react/assets/70185413/315cd0f2-683f-4807-89c9-ab58764ea1b3">

TIP: This is my first time submitting a contribution to React. If anything that needs to be done is missing, please remind me and I will handle it as soon as possible

2024-07-02 01:34 UTC, GrinZero commented
cc @sebmarkbage or anybody? I hope this PR can catch everyone's attention

2024-07-11 00:55 UTC, josephsavona reviewed
Thanks for the PR. We're not opposed to exploring changes to the output format, but:
a) We want to find one format that is the best combination of code size and runtime performance, not have long-lived feature flags for people to choose.
b) If we use higher-level helpers, the cost of those has to be carefully tested to ensure they don't regress other properties. 

In this case, I'm concerned that this reintroduces lots of array and closure allocations in exchange for reduced code size. So far we've been mostly memory neutral, but this could easily make the compiled output use more memory than before. 

If you finish implementing this such that CI is green, we can try benchmarking it. But we'd only be move forward if the results are positive.

2024-07-11 00:57 UTC, josephsavona commented on compiler/packages/react-compiler-runtime/src/index.ts
> +  })();
this is really inefficient. Let's turn this into static code without the unnecessary closure allocations. ie

```js
let hasChange = false;
for (let i = 0; i < conditionIndices.length; i++) {
   ...
   if (cache[conditionIndices[i]] !== conditionTargets[i]) {
     hasChange = true;
     break;
   }
   ...
}
```

2024-07-11 01:00 UTC, josephsavona requested changes
requesting changes to get this to pass CI before we can proceed with anything

2024-10-09 02:11 UTC, closed without merging