[compiler] Make ref enforcement on by default
facebook/react pull request #30716
Opened 2024-08-15 18:25 UTC by mvitousek

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #30716
* #30724
* #30723
* #30715
* #30714
* #30713

Summary:
The change earlier in this stack makes it less safe to have ref enforcement disabled. This diff enables it by default.

2024-08-15 19:06 UTC, josephsavona commented on compiler/packages/babel-plugin-react-compiler/src/__tests__/parseConfigPragma-test.ts
> +      '@enableUseTypeAnnotations @validateRefAccessDuringRender:false @validateNoSetStateInRender:false',
nit: the idea of this test was to test both the `@flag`, `@flag:true`, and `@flag:false` cases, so maybe choose a different off-by-default flag to use instead

2024-08-15 19:07 UTC, josephsavona commented on compiler/packages/babel-plugin-react-compiler/src/__tests__/fixtures/compiler/preserve-memo-validation/error.preserve-use-memo-ref-missing-ok.expect.md
> +  }, []);
hmm this actually seems like it should be allowed: this could be returning a callback that is only called in an event/effect

2024-08-15 19:08 UTC, josephsavona requested changes
Awesome, i commented earlier in the stack about enabling this by default so we're on the same page. But see comments - i think we're a bit too strict right now and should relax the case of a hook returning a callback which accesses a ref.

2024-08-16 16:49 UTC, mvitousek commented
> Awesome, i commented earlier in the stack about enabling this by default so we're on the same page. But see comments - i think we're a bit too strict right now and should relax the case of a hook returning a callback which accesses a ref.

Good call, addressed in [30724](https://github.com/facebook/react/pull/30724)

2024-08-16 17:06 UTC, josephsavona approved these changes
awesome job

2024-08-16 17:27 UTC, merged

2024-09-04 13:18 UTC, lukpsaxo commented
This change has on the whole exposed lots of potential bugs for us - thanks.

The main case where we see alot of non bugs is passing the ref into a custom hook or react hook (useImperitiveHandle). In these cases it seems it usually uses useLayoutEffect and then reads the ref inside useLayoutEffect.

should it be relaxed to allow passing refs to hooks?