[DevTools] Use Unicode Atom Symbol instead of Atom Emoji
facebook/react pull request #30832
Opened 2024-08-28 04:18 UTC by sebmarkbage

This reverts #19603.

Before:
<img width="724" alt="Screenshot 2024-08-28 at 12 07 29 AM" src="https://github.com/user-attachments/assets/0613088f-c013-4f1c-92c3-fbdae8c1f109">

After:
<img width="771" alt="Screenshot 2024-08-28 at 12 08 13 AM" src="https://github.com/user-attachments/assets/eef21bee-d11f-4f0a-9147-053a163f720f">

Consensus seems to be that while the purple on is a bit clearer and easier to read. The purple is not on brand so it doesn't look like React. It looks ugly. It's distracting (too eye catching). Taking away attention from other tabs in an unfair way.

It also gets worse with more tabs added. We plan on both adding another tab and panes inside other tabs (elements/sources) soon. Each needs to be marked somehow as part of React but spelling it out is too long. Putting inside a second tab means two clicks and takes away real-estate from our extension and doesn't solve the problem with extension panes in other tabs. We also plan on adding multiple different tracks to the Performance tab which also needs a name other than just React and spelling out React as a prefix is too long. The Emoji is too distracting. So it seems best to uniformly apply the symbol - albeit it might just look like a dot to many.

2024-08-28 08:30 UTC, eps1lon approved these changes
Sooo, are you gonna work on adding a React emoji to the unicode standard? 😄 

I don't have a preference here. It's either ugly or unreadable.

2024-08-28 11:28 UTC, hoxyq reviewed
There is a parameter for [`chrome.devtools.panels.create`](https://developer.chrome.com/docs/extensions/reference/api/devtools/panels#method-create), which allows to specify path to an icon, but looks like its not working on Chrome.

Looks like it [is deprecated](https://issues.chromium.org/issues/41126397), and the docs were not updated. Only Firefox is correctly displaying the extension icon left to the panel name.

I am not sure about this change, though, would adding "React" as prefix make it take too much space?

2024-08-28 12:45 UTC, hoxyq requested changes
Can we have some time to discuss this, before actually committing and potentially changing this multiple times?

I think the ideal state for us is to ask Chrome team if `iconPath` will ever be supported again, so that we can display correct React logo.

If its deprecated and there are no plans for supports icons in third party extensions panels, then I would prefer having "React" as a prefix in our panels names, I don't think the spelling is too long, and it looks native to other built-in panels.

I don't know about the plans on naming the third panel, but it should not be long as well, something like "React Suspense", "React Suspense Sandbox" is alright. Although the unicode atom symbol looks more similar to original React logo, it is barely visible.
![Screenshot 2024-08-28 at 13 44 47](https://github.com/user-attachments/assets/6e50a087-3e2c-47dc-b540-35259ebe4c06)

2024-08-28 16:42 UTC, gaearon commented
It's not great to have a prefix because it stills screen estate from other tabs. I.e. Chrome would literally show fewer tabs on the screen because of this.

2024-08-28 17:30 UTC, huntie commented
Adding a strong vote for leave as is 😅 Agree that `iconPath` would be ideal, and we should try to pursue this.

2024-08-28 17:36 UTC, hoxyq commented
> It's not great to have a "React" prefix because it steals screen estate from other tabs. I.e. Chrome would literally show fewer tabs on the screen because of this.

Chrome users can re-arrange panels, so that the most important ones or the most used ones are on the left.
I think we just need to decide what we are optimizing: the spelling length or the recognition / branding.

Ideally, it should have been just React logo to the left of the panel name, but it is currently only supported in Firefox.

2024-08-28 18:47 UTC, sebmarkbage commented
I absolutely don't want to leave it as is. It makes me embarrassed to work on it. It really looks like shit.

I'm actually ok with just removing the icon completely and putting the logo in the panel itself. You'd have to learn that "Components" means React Components and "Suspense" means React Suspense. "Profiler" means React Profiler somehow.

Even if you reorder them "React Components", "React Suspense" and "React Profiler" is almost enough to take up the whole width in a right-docked panel.

Keep in mind that it's not just about these two tabs. It's about the panes integrated into the other native tabs too. For example I want to add a "Components" pane in the Elements panel. That one defaults to a horizontal tab bar in smaller sized pane. We could just name it "Components" there too. I'm ok with that but it's a bit broad.

Then there's the Performance tab. It would have things like Client Components and Server Components tracks. That's already kind of long even without the React prefix and the Performance tab has this existing problem that the earliest left-most things.

Even if we get the iconPath added back it's probably not getting added to the panes and the performance tab too. So we don't have a consistent design language to work with. The unicode icon is a nice hack to build that consistency without taking up real-estate.

But I'm also ok just removing the icon and word React completely. When working on a React centric app that's typically your primary focus so it's implied anyway. It's like the whole thing is the React DevTools.

2024-08-28 18:49 UTC, sebmarkbage commented
Btw the icon in Firefox looks terrible in light mode too. Is there a way to make that use a transparent background instead that can work in both?

2024-08-28 19:12 UTC, sebmarkbage commented
If we remove the icon we can maybe squeeze in the logo in the top left corner where the selector is and next to the record button. The way I was imagining the Components pane in Elements was that the top would be a short list of Components so wouldn't work there. It also wouldn't work in the Performance tab. Those are maybe implied by Client Components and Server Components (there's a third one to be named too) or could use the icon only in that case but then there's nothing to carry it over.

2024-08-28 19:29 UTC, josephsavona commented
Could we have a single "React" tab, within which we have components and profiler and whatever other tabs we choose to add later? Just "React" makes it super clear.

2024-08-28 19:36 UTC, hoxyq commented
> Btw the icon in Firefox looks terrible in light mode too. Is there a way to make that use a transparent background instead that can work in both?

I think Firefox is using one of the icons, which are defined in the manifest file. Updating these icons to have transparent background should fix it, but there could be other implications by having transparent background in the extension logo.

2024-08-28 19:42 UTC, hoxyq commented
> Could we have a single "React" tab, within which we have components and profiler and whatever other tabs we choose to add later? Just "React" makes it super clear.

It is possible, and I think this is another case we should consider.

The code for it is already there - we do render inner tabs (Components and Profiler) in React DevTools UI for React Native (both in legacy standalone electron shell and in new Chrome DevTools-based approach).

One potential downside is cross-panel deeplinking in Chrome DevTools: we want to be able to navigate to / from Performance panel, for example. Although it would probably not affect the complexity of the potential implementation, we could still implement inner tab navigation by parsing deeplink, having multiple panels is more obvious to the user, because you only have single level of depth for panels.

2024-08-28 19:51 UTC, sebmarkbage commented
> Could we have a single "React" tab, within which we have components and profiler and whatever other tabs we choose to add later? Just "React" makes it super clear.

The goal with all of this work (performance.measure instead of React Profiler, elements panel, server console logs, console.createTask for native stacks everywhere etc) is to great an integrated experience that works throughout the DevTools. Then there's also Next.js DevTools tabs etc.

React is only a small part of a larger system. So the idea of centralizing around you just opening the "React" tab and staying there is counter to that principle. It's more like the React Suspense tab is parallel to a theoretical Next.js Network tab than it is to the React Components tab.

Given that the tabs are customizable and some tabs are more useful than others for specific work I don't think this is good. For example, I would likely hide the the React Components tab and just bring forward the React Suspense tab and the Elements tab. I wouldn't want to click React tab and then Suspense tab every time I want to get there.

2024-08-28 19:56 UTC, josephsavona commented
@sebmarkbage That makes sense for why not grouping into a React tab. I think it's helpful for docs and new users if there is something a bit more specific than just "Components" as a tab name, and "React Components" is too long. The unicode symbol is a bit more subtle (i've never loved the current emoji either). I'm supportive of this change. 

If we can use the actual logo later great, but we don't have to block on it.

2024-08-28 20:01 UTC, sebmarkbage commented
Tbh, I don't love the real icons in Firefox neither. It's very cluttered. I think Chrome probably did the right thing by removing them to avoid too many colorful icons there but maybe should've banned emojis at the same time. But then they added the green Node.js icon (which is great but green). 🙈

2024-08-28 20:05 UTC, sebmarkbage commented
How do we feel about adding it to the end? That way when they're presented in lists the letters line up:

<img width="477" alt="Screenshot 2024-08-28 at 4 03 30 PM" src="https://github.com/user-attachments/assets/fc56d2ba-b9d5-4bed-9cb8-846ec10b1dd2">

This happens in Performance tab and extension panes in Sources tab too.

There's precedence in Chrome itself for icons at the end for example for Experimental features.

<img width="648" alt="Screenshot 2024-08-28 at 4 04 21 PM" src="https://github.com/user-attachments/assets/96480123-e761-458d-bc3c-303191517214">

2024-08-28 20:21 UTC, josephsavona commented
End seems fine too

2024-08-28 22:58 UTC, josephsavona approved these changes

2024-08-29 10:03 UTC, hoxyq commented
I still don't see a reason why we are optimizing spelling size, but also agree that it should not block this PR from landing. Whatever we decide on styling, I would prefer to change it only once, and then maybe migrate to using React logo as an icon, in case this will ever be supported again by Chrome.

2024-09-10 04:09 UTC, merged