fix: Null check added when resolving event's priority
facebook/react pull request #31044
Opened 2024-09-24 14:46 UTC by classicdocs

## Summary

I wanted to migrate from React 17 to React 18 and experienced issues with rendering when using new root API.

When `window.event` is `null`, ` Uncaught TypeError: Cannot read properties of null (reading 'type')`error can be thrown when calling render function.

✅  Example with React 17 where nothing breaks and component is rendered correctly:
https://jsfiddle.net/9zg3t4mc/1/

❌ Example with React 18 where error is thrown and component is not rendered:
https://jsfiddle.net/92wtjb0g/

## How did you test this change?

I run `yarn build` and then use `React-prod.js` inside fiddle that is throwing an error and with this change render is working now.
![image](https://github.com/user-attachments/assets/ed273cbf-e0cc-4ee2-abc1-359ff508fbb9)

2024-09-24 15:46 UTC, josephsavona commented
Hmm, the repro you provided is overriding a global to be null. I think that shouldn't ever happen in practice, though. Is there a legitimate case in some supported browser where the event can be null as opposed to undefined?

2024-09-24 15:57 UTC, classicdocs commented
@josephsavona Thanks for quick answer. Yes, indeed it shouldn't be overwritten, but in real world I have experienced that client's app somehow is overriding this and I'm injecting a script where I'm rendering react app and it will give me this error.

2024-09-27 15:27 UTC, josephsavona commented
Fair. This seems reasonable to add, but we also need a regression test. Can you add on here?

2024-09-27 15:27 UTC, josephsavona requested changes
Requesting changes for a regression test

2024-09-27 16:03 UTC, classicdocs commented
@josephsavona I have added a test to cover this case. Cheers

2025-01-02 18:05 UTC, closed without merging

2025-04-24 11:42 UTC, okejminja commented
Any news about merging this PR? I've experienced similar issues to what @classicdocs has described.

2025-05-15 19:55 UTC, classicdocs commented
bump

2025-05-15 19:57 UTC, classicdocs commented
@josephsavona Can we reopen this PR ?