fix(react-compiler): optimize components declared with arrow function…
facebook/react pull request #31792
Opened 2024-12-15 22:25 UTC by dimaMachina

fixes https://github.com/facebook/react/issues/31601 https://github.com/facebook/react/issues/31639 cc @josephsavona

2025-02-27 16:54 UTC, josephsavona requested changes
Thanks for the contribution! Please see comments

2025-02-27 16:54 UTC, josephsavona commented on compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts
> +  }
I missed this PR the first time around, my apologies. This is an overly narrow solution and needs to be more robust. Let's do the following:

1. Extract out a helper that takes an Expression and returns a boolean for whether its possibly a React node or not. This can reuse the `switch (argument.type) { ... }` from the current ReturnStatement case.
2. Reuse this helper in the existing ReturnStatement case
3. Expand the ArrowFunctionExpression case to check if the body is an expresssion, and if so use the new helper. otherwise traverse with skipNestedFunctions.

2025-02-27 18:55 UTC, dimaMachina commented on compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts
> +  }
No worries Joseph, thanks for your detailed feedback 🤩

> Extract out a helper that takes an Expression and returns a boolean for whether its possibly a React node or not. This can reuse the switch (argument.type) { ... } from the current ReturnStatement case.

extracted as `isNonNode` function in https://github.com/facebook/react/pull/31792/commits/d0f5b19a5416aa214287128c8e612b43aec58702

https://github.com/facebook/react/blob/d0f5b19a5416aa214287128c8e612b43aec58702/compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts#L996-L1010

> Reuse this helper in the existing ReturnStatement case

https://github.com/facebook/react/blob/d0f5b19a5416aa214287128c8e612b43aec58702/compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts#L1029-L1032

> Expand the ArrowFunctionExpression case to check if the body is an expresssion, and if so use the new helper. otherwise traverse with skipNestedFunctions.

I can't get this to work, seems `node.traverse#ArrowFunctionExpression` isn't called for the root node

2025-02-27 19:15 UTC, dimaMachina commented on compiler/packages/babel-plugin-react-compiler/src/Entrypoint/Program.ts
> +  }
also removed useless `hasReturn` variable in https://github.com/facebook/react/pull/31792/commits/e0c93642c525e6aad1b8ee924cb3d72e542ead2f

2025-03-16 11:04 UTC, dimaMachina commented
@josephsavona friendly ping

2025-03-21 23:46 UTC, merged

2025-03-21 23:46 UTC, josephsavona commented
Thanks for the fix!