fix(react-compiler): implement NumericLiteral as ObjectPropertyKey
facebook/react pull request #31791
Opened 2024-12-15 20:28 UTC by dimaMachina

fix https://x.com/dimaMachina_/status/1867706100264652875 cc @josephsavona

2025-01-09 19:03 UTC, abhishekgautam95 commented
I've identified an issue where the React compiler does not correctly handle NumericLiteral as an object property key. This can lead to incorrect transformations or errors when compiling code that uses numeric keys in objects.

Problem Statement

Consider the following JavaScript code:
JavaScript

const obj = {
  123: 'value'
};

The key 123 is a NumericLiteral. When this code is processed by the compiler, it should correctly transform and handle 123 as an object property key. However, the current implementation does not handle NumericLiteral properly, resulting in incorrect transformations.

Proposed Solution

To address this issue, we need to implement logic in the React compiler to detect and handle NumericLiteral as an object property key. The steps involved are:

    Detect NumericLiteral: Modify the compiler's AST transformation logic to detect when a key is a NumericLiteral.
    Convert to String: Convert the NumericLiteral to a string, as JavaScript object keys are strings.
    Use as Key: Use the converted string as the object property key.

Code Changes

    Modify the Object Property Key Handling

Create or update the file packages/react-compiler/src/ObjectPropertyKey.js:
JavaScript

import * as t from '@babel/types';

/**
 * Creates an object property key, converting NumericLiteral to StringLiteral.
 * @param {t.Node} key - The AST node representing the key.
 * @returns {t.StringLiteral | t.Identifier} - The transformed key.
 * @throws {Error} - If the key type is unsupported.
 */
function createObjectPropertyKey(key) {
  if (t.isNumericLiteral(key)) {
    // Convert NumericLiteral to string to be used as object property key
    return t.stringLiteral(String(key.value));
  }
  if (t.isStringLiteral(key) || t.isIdentifier(key)) {
    // Return the key as-is for StringLiteral and Identifier
    return key;
  }
  // Throw an error for unsupported key types
  throw new Error(`Unsupported key type: ${key.type}`);
}

// Usage in the code
const objectProperty = t.objectProperty(
  createObjectPropertyKey(key),
  value
);

export default createObjectPropertyKey;

    Add Unit Tests

Create or update the file packages/react-compiler/src/__tests__/ObjectPropertyKey.test.js:
JavaScript

import { transform } from '@babel/core';
import plugin from '../ObjectPropertyKey';

test('should handle NumericLiteral as ObjectPropertyKey', () => {
  const code = `
    const obj = {
      123: 'value'
    };
  `;

  const output = transform(code, { plugins: [plugin] });

  expect(output.code).toMatchInlineSnapshot(`
    "const obj = {
      '123': 'value'
    };"
  `);
});

test('should handle negative NumericLiteral as ObjectPropertyKey', () => {
  const code = `
    const obj = {
      -123: 'value'
    };
  `;

  const output = transform(code, { plugins: [plugin] });

  expect(output.code).toMatchInlineSnapshot(`
    "const obj = {
      '-123': 'value'
    };"
  `);
});

test('should handle floating-point NumericLiteral as ObjectPropertyKey', () => {
  const code = `
    const obj = {
      123.456: 'value'
    };
  `;

  const output = transform(code, { plugins: [plugin] });

  expect(output.code).toMatchInlineSnapshot(`
    "const obj = {
      '123.456': 'value'
    };"
  `);
});

test('should handle StringLiteral as ObjectPropertyKey', () => {
  const code = `
    const obj = {
      'key': 'value'
    };
  `;

  const output = transform(code, { plugins: [plugin] });

  expect(output.code).toMatchInlineSnapshot(`
    "const obj = {
      'key': 'value'
    };"
  `);
});

test('should throw an error for unsupported key types', () => {
  const code = `
    const obj = {
      [true]: 'value'
    };
  `;

  expect(() => transform(code, { plugins: [plugin] })).toThrowError(
    'Unsupported key type: BooleanLiteral'
  );
});

    Integration

Ensure the createObjectPropertyKey function is integrated into the compiler's transformation pipeline. For example:
JavaScript

// Example usage in a transformer
import createObjectPropertyKey from './ObjectPropertyKey';

function transformObjectProperty(node) {
  const key = createObjectPropertyKey(node.key);
  const value = transformValue(node.value); // Assume this function exists
  return t.objectProperty(key, value);
}

    Documentation

Update the compiler's documentation to reflect this change. Add a section explaining how numeric keys are handled:
Markdown

### **Handling Numeric Keys in Objects**

The React compiler now supports `NumericLiteral` as object property keys. Numeric keys are automatically converted to strings to align with JavaScript's behavior. For example:

```javascript
const obj = {
  123: 'value'
};

is transformed to:
JavaScript

const obj = {
  '123': 'value'
};

Supported key types:

    NumericLiteral
    StringLiteral
    Identifier

Unsupported key types (e.g., BooleanLiteral, TemplateLiteral) will throw an error.
Code

---

### **How to Use**

1. Copy the `ObjectPropertyKey.js` file into your `packages/react-compiler/src/` directory.
2. Copy the `ObjectPropertyKey.test.js` file into your `packages/react-compiler/src/__tests__/` directory.
3. Integrate the `createObjectPropertyKey` function into your compiler's transformation logic.
4. Run the tests to ensure everything works as expected:
   ```bash
   npm test

    Update your documentation to reflect the changes.

Example Output

Input Code:
JavaScript

const obj = {
  123: 'value',
  -456: 'value',
  789.123: 'value',
  'key': 'value'
};

Transformed Code:
JavaScript

const obj = {
  '123': 'value',
  '-456': 'value',
  '789.123': 'value',
  'key': 'value'
};

2025-01-10 04:27 UTC, dimaMachina commented
friendly ping @josephsavona as you requested to created PR with fix in twitter

2025-01-10 04:42 UTC, abhishekgautam95 commented
It's.
Can you give me feedback on my comment please

On Fri, 10 Jan, 2025, 09:58 Dimitri POSTOLOV, ***@***.***>
wrote:

> friendly ping @josephsavona <https://github.com/josephsavona> as you
> requested to create PR with fix in twitter
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/react/pull/31791#issuecomment-2581718143>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A46NNG3CIETDRQFIOQFKO4D2J5D57AVCNFSM6AAAAABTU3XIUCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOBRG4YTQMJUGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-01-10 04:53 UTC, josephsavona commented
Yeah, will take a look tomorrow

2025-01-10 16:36 UTC, josephsavona commented on compiler/packages/babel-plugin-react-compiler/src/__tests__/fixtures/compiler/numeric-literal-as-object-property-key.js
> +}
please add a fixture here so that we can test evaluation with/without compilation:

```
export const FIXTURE_ENTRYPOINT = {
  fn: Test,
  params: [{}],
};
```

2025-01-10 16:36 UTC, josephsavona commented on compiler/packages/babel-plugin-react-compiler/src/__tests__/fixtures/compiler/numeric-literal-as-object-property-key.js
> +}
also be sure to update fixtures after this

2025-01-10 16:36 UTC, josephsavona requested changes
Just one change, then this should be good to land. Thanks!

2025-01-10 16:40 UTC, abhishekgautam95 commented
Thanks for taking your time on my little efforts🙏🙏

On Fri, 10 Jan, 2025, 22:07 Joseph Savona, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Just one change, then this should be good to land. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/react/pull/31791#pullrequestreview-2542927612>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A46NNG53CXXOP2TJDCEOQN32J7ZK7AVCNFSM6AAAAABTU3XIUCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNBSHEZDONRRGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-01-10 16:59 UTC, dimaMachina commented on compiler/packages/babel-plugin-react-compiler/src/__tests__/fixtures/compiler/numeric-literal-as-object-property-key.js
> +}
Thank you! Updated! Could you also review my other contribution to the react compiler? https://github.com/facebook/react/pull/31792

I just pushed there similar change 🙂

2025-02-27 11:34 UTC, dimaMachina commented
@josephsavona friendly ping 🙏

2025-02-27 16:47 UTC, josephsavona approved these changes

2025-02-27 16:59 UTC, mofeiZ commented
Thanks for the contribution! Please run `yarn prettier` at the root (`react/`) to format changed files before landing

2025-02-27 17:16 UTC, dimaMachina commented
@mofeiZ ty, done!

2025-03-16 11:04 UTC, dimaMachina commented
@mofeiZ friendly ping

2025-03-17 22:44 UTC, dimaMachina commented on compiler/packages/babel-plugin-react-compiler/src/HIR/BuildHIR.ts
> +    };
@mofeiZ thanks for your review, done in https://github.com/facebook/react/pull/31791/commits/5499ae1c47a2293a32aa1cd184785f74e32934ea

Should I move `destructuring assignment` test to a separate file?

2025-03-17 23:03 UTC, mofeiZ commented on compiler/packages/babel-plugin-react-compiler/src/HIR/BuildHIR.ts
> +    };
Awesome, thanks for the quick fix! Just started a test run and will merge once everything passes

> Should I move destructuring assignment test to a separate file?
This should be fine.

2025-03-17 23:30 UTC, merged

2025-03-17 23:35 UTC, dimaMachina commented
@mofeiZ huge thanks to finally getting this merged 🥳 would you have time to review my other tiny contribution to react compiler in https://github.com/facebook/react/pull/31792 ? 🙏