[complier] bugfix, constantPropagation, remove phi node with empty operands.
facebook/react pull request #31940
Opened 2024-12-31 03:30 UTC by asmjmp0

## Summary

test code:
```javascript
function test() {
    let v3, v4, acc;
    v3 = false;
    v4 = v3;
    acc = v3;
    if (acc) {
      acc = true;
      v3 = acc;
    }
    if (acc) {
      v3 = v4;
    }
    v4 = v3;
}
```
after twice constant propagation, we can get the hir code, before invoke `eliminateRedundantPhi` method. 
```
bb1 (block):
  [1] <unknown> $31 = DeclareLocal Let <unknown> v3$30
  [2] <unknown> $33 = DeclareLocal Let <unknown> v4$32
  [3] <unknown> $35 = DeclareLocal Let <unknown> acc$34
  [4] <unknown> $36 = false
  [5] <unknown> $38 = StoreLocal Reassign <unknown> v3$37 = <unknown> $36
  [6] <unknown> $39 = false
  [7] <unknown> $41 = StoreLocal Reassign <unknown> v4$40 = <unknown> $39
  [8] <unknown> $42 = false
  [9] <unknown> $44 = StoreLocal Reassign <unknown> acc$43 = <unknown> $42
  [10] <unknown> $45 = false
  [11] <unknown> $53 = false
  [12] Goto bb4
bb4 (block):
  predecessor blocks: bb1
  <unknown> v3$58: phi()
  [13] <unknown> $60 = false
  [14] <unknown> $62 = StoreLocal Reassign <unknown> v4$61 = <unknown> $60
  [15] <unknown> $63 = <undefined>
  [16] Return <unknown> $63
```
we can see the phi node `<unknown> v3$58: phi()` with empty operands, which make `eliminateRedundantPhi` method error.
```
CompilerError [ReactCompilerError]: Invariant: Expected phis to be non-empty
```
so I remove the phi node with empty operands.

## How did you test this change?

I run the command `yarn test` at `compiler` dictionary, and all tests passed.

2024-12-31 04:59 UTC, josephsavona requested changes
Thanks for the bug report and fix! To get this landed we need a fixture that reproduces the issue. Please add a test case in https://github.com/facebook/react/tree/main/compiler/packages/babel-plugin-react-compiler/src/__tests__/fixtures/compiler and update snapshot fixtures. Make sure the test case fails without the fix (please include what the exact error was wo the fix, or what the incorrect output was).

2024-12-31 11:07 UTC, dimaMachina commented
```diff
function component() {
  let v3, v4, acc;
  v3 = false;
  v4 = v3;
  acc = v3;
-  if (acc) {
-    acc = true;
-    v3 = acc;
-  }
-  if (acc) {
-    v3 = v4;
-  }
  v4 = v3;
  return [acc,v3,v4];
}
```

these `if` statements will never be executed since `v3 = false` and `acc = v3`, maybe it is better to add some working test fixture?

2024-12-31 12:19 UTC, asmjmp0 commented
> ```diff
> function component() {
>   let v3, v4, acc;
>   v3 = false;
>   v4 = v3;
>   acc = v3;
> -  if (acc) {
> -    acc = true;
> -    v3 = acc;
> -  }
> -  if (acc) {
> -    v3 = v4;
> -  }
>   v4 = v3;
>   return [acc,v3,v4];
> }
> ```
> 
> these `if` statements will never be executed since `v3 = false` and `acc = v3`, maybe it is better to add some working test fixture?

because of these unreachable if statements that phi nodes with empty operands are generated. If these statements are removed, then it will be impossible to reproduce this bug.

2024-12-31 12:35 UTC, dimaMachina commented
> because of these unreachable if statements that phi nodes with empty operands are generated. If these statements are removed, then it will be impossible to reproduce this bug.

Got it, thank you! I simplified the test fixture to

```js
function Component() {
  let foo;
  let bar = false;

  if (bar) bar = true;
  if (bar) foo = 0;
  return foo;
}
```

And got the same error `Invariant: Expected phis to be non-empty` [preview](https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRANgjkWhBADc7Ilx5EARgEMYRALx8pnMAmGYRRPGiL1pMZnvlEcMKKo1ade5vwhGADGtEwesYrbUBfEJ6A)

But, if I try to reproduce my test fixture in your preview, I got `Invariant: [hoisting] Expected value for identifier to be initialized. foo$27 (7:7)` [this pr preview](https://react-compiler-playground-4qgjd8zwb-fbopensource.vercel.app/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRANgjkWhBADc7Ilx5EARgEMYRALx8pnMAmGYRRPGiL1pMZnvlEcMKKo1ade5vwhGADGtEwesYrbUBfEJ6A)

2024-12-31 12:48 UTC, asmjmp0 commented
> > because of these unreachable if statements that phi nodes with empty operands are generated. If these statements are removed, then it will be impossible to reproduce this bug.
> 
> Got it, thank you! I simplified the test fixture to
> 
> ```js
> function Component() {
>   let foo;
>   let bar = false;
> 
>   if (bar) bar = true;
>   if (bar) foo = 0;
>   return foo;
> }
> ```
> 
> And got the same error `Invariant: Expected phis to be non-empty` [preview](https://playground.react.dev/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRANgjkWhBADc7Ilx5EARgEMYRALx8pnMAmGYRRPGiL1pMZnvlEcMKKo1ade5vwhGADGtEwesYrbUBfEJ6A)
> 
> But, if I try to reproduce my test fixture in your preview, I got `Invariant: [hoisting] Expected value for identifier to be initialized. foo$27 (7:7)` [this pr preview](https://react-compiler-playground-4qgjd8zwb-fbopensource.vercel.app/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRANgjkWhBADc7Ilx5EARgEMYRALx8pnMAmGYRRPGiL1pMZnvlEcMKKo1ade5vwhGADGtEwesYrbUBfEJ6A)

perhaps you need to assign an initial value to foo, because after constant propagation and unreachable statements removed, and the variable foo is not assigned a value but is directly returned.

2024-12-31 12:52 UTC, dimaMachina commented
same error if[ I initialize ](https://react-compiler-playground-4qgjd8zwb-fbopensource.vercel.app/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRANgjkWhBCIBeIpiidOAbnZEuPIgCMAhjGF8lnMAmmYZRPGiL1lMZibU4YUbXoNGTzfoJEAGHbJg9YxJzoC+IH5AA)

2024-12-31 16:29 UTC, asmjmp0 commented
> same error if[ I initialize ](https://react-compiler-playground-4qgjd8zwb-fbopensource.vercel.app/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRANgjkWhBCIBeIpiidOAbnZEuPIgCMAhjGF8lnMAmmYZRPGiL1lMZibU4YUbXoNGTzfoJEAGHbJg9YxJzoC+IH5AA) ah I got what you meant

after review the case you said, I found that the core of the issue lies in the merge pass, which was not fixing the phi nodes of the successor blocks. This caused the constant propagation pass to mistakenly believe there were no predecessor blocks, leading to the deletion of operands. I have now resubmitted the code, passed the local test cases, could you please take another look?

2024-12-31 16:55 UTC, dimaMachina commented
> > same error if[ I initialize ](https://react-compiler-playground-4qgjd8zwb-fbopensource.vercel.app/#N4Igzg9grgTgxgUxALhAMygOzgFwJYSYAEAwhALYAOhCmOAFAJRHAA6xRANgjkWhBCIBeIpiidOAbnZEuPIgCMAhjGF8lnMAmmYZRPGiL1lMZibU4YUbXoNGTzfoJEAGHbJg9YxJzoC+IH5AA) ah I got what you meant
> 
> after review the case you said, I found that the core of the issue lies in the merge pass, which was not fixing the phi nodes of the successor blocks. This caused the constant propagation pass to mistakenly believe there were no predecessor blocks, leading to the deletion of operands. I have now resubmitted the code, passed the local test cases, could you please take another look?

nice, now looks good to me too 🚀

2025-01-02 19:13 UTC, josephsavona commented
Thank you for finding this bug! The fix here is subtle and i'm not sure exactly where the best place would be, but my instinct is that the fix should be in constant propagation. Also, as written this requires O(n^2) iterations over the blocks, which seems inefficient. Let me take a look.

2025-01-02 19:25 UTC, josephsavona commented
Ok I looked into it, and it does make sense to fix in MergeConsecutiveBlocks but we should iterate once. I put this up in #31959

2025-01-03 08:23 UTC, closed without merging